services:
  dotspasswordmanager.web.api:
    image: ghcr.io/giorgiodots/dots-password-manager:prod
    container_name: dotspasswordmanagerwebapi
    build:
      context: .
      dockerfile: DotsPasswordManager.Web.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXP_MINUTES=${JWT_EXP_MINUTES}
      - JWT_REFRESH_TOKEN_EXP_DAYS=${JWT_REFRESH_TOKEN_EXP_DAYS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DB_CONNECTION_STRING_FILE=/run/secrets/db_connection_string
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - CRYPTO_BASE_64_KEY_FILE=/run/secrets/crypto_key
    secrets:
      - db_connection_string
      - jwt_secret
      - crypto_key

secrets:
  db_connection_string:
    file: ./secrets/db_connection_string.secret
  jwt_secret:
    file: ./secrets/jwt_secret.secret
  crypto_key:
    file: ./secrets/crypto_key.secret