/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { userSavedPasswordGetPasswordsEndpoint } from '../fn/passwords/user-saved-password-get-passwords-endpoint';
import { UserSavedPasswordGetPasswordsEndpoint$Params } from '../fn/passwords/user-saved-password-get-passwords-endpoint';
import { UserSavedPasswordGetPasswordsResponse } from '../models/user-saved-password-get-passwords-response';

@Injectable({ providedIn: 'root' })
export class PasswordsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userSavedPasswordGetPasswordsEndpoint()` */
  static readonly UserSavedPasswordGetPasswordsEndpointPath = '/passwords';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userSavedPasswordGetPasswordsEndpoint()` instead.
   *
   * This method doesn't expect any request body.
   */
  userSavedPasswordGetPasswordsEndpoint$Response(params?: UserSavedPasswordGetPasswordsEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<UserSavedPasswordGetPasswordsResponse>> {
    return userSavedPasswordGetPasswordsEndpoint(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userSavedPasswordGetPasswordsEndpoint$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userSavedPasswordGetPasswordsEndpoint(params?: UserSavedPasswordGetPasswordsEndpoint$Params, context?: HttpContext): Observable<UserSavedPasswordGetPasswordsResponse> {
    return this.userSavedPasswordGetPasswordsEndpoint$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserSavedPasswordGetPasswordsResponse>): UserSavedPasswordGetPasswordsResponse => r.body)
    );
  }

}
