/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserSavedPasswordUpdatePasswordRequest } from '../../models/user-saved-password-update-password-request';
import { UserSavedPasswordUpdatePasswordResponse } from '../../models/user-saved-password-update-password-response';

export interface UserSavedPasswordUpdatePasswordEndpoint$Params {
  id: string;
      body: UserSavedPasswordUpdatePasswordRequest
}

export function userSavedPasswordUpdatePasswordEndpoint(http: HttpClient, rootUrl: string, params: UserSavedPasswordUpdatePasswordEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<UserSavedPasswordUpdatePasswordResponse>> {
  const rb = new RequestBuilder(rootUrl, userSavedPasswordUpdatePasswordEndpoint.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserSavedPasswordUpdatePasswordResponse>;
    })
  );
}

userSavedPasswordUpdatePasswordEndpoint.PATH = '/passwords/edit/{id}';
