/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAuthResetPasswordRequestRequest } from '../../models/user-auth-reset-password-request-request';
import { UserAuthResetPasswordRequestResponse } from '../../models/user-auth-reset-password-request-response';

export interface UserAuthResetPasswordRequestEndpoint$Params {
  body: UserAuthResetPasswordRequestRequest;
}

export function userAuthResetPasswordRequestEndpoint(
  http: HttpClient,
  rootUrl: string,
  params: UserAuthResetPasswordRequestEndpoint$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<UserAuthResetPasswordRequestResponse>> {
  const rb = new RequestBuilder(
    rootUrl,
    userAuthResetPasswordRequestEndpoint.PATH,
    'post'
  );
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<UserAuthResetPasswordRequestResponse>;
      })
    );
}

userAuthResetPasswordRequestEndpoint.PATH = '/auth/reset-password-request';
