/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserRefreshTokenRequest } from '../../models/user-refresh-token-request';
import { UserRefreshTokenResponse } from '../../models/user-refresh-token-response';

export interface UserRefreshTokenEndpoint$Params {
      body: UserRefreshTokenRequest
}

export function userRefreshTokenEndpoint(http: HttpClient, rootUrl: string, params: UserRefreshTokenEndpoint$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRefreshTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, userRefreshTokenEndpoint.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserRefreshTokenResponse>;
    })
  );
}

userRefreshTokenEndpoint.PATH = '/auth/refresh-token';
