/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRequestRouteImport } from './routes/auth/reset-password-request'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthonlyNoAuthRouteRouteImport } from './routes/auth/(only-no-auth)/route'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as protectedSavedPasswordsIndexRouteImport } from './routes/(protected)/saved-passwords/index'
import { Route as AuthonlyNoAuthRegisterRouteImport } from './routes/auth/(only-no-auth)/register'
import { Route as AuthonlyNoAuthLoginRouteImport } from './routes/auth/(only-no-auth)/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRequestRoute =
  AuthResetPasswordRequestRouteImport.update({
    id: '/auth/reset-password-request',
    path: '/auth/reset-password-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthonlyNoAuthRouteRoute = AuthonlyNoAuthRouteRouteImport.update({
  id: '/auth/(only-no-auth)',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSavedPasswordsIndexRoute =
  protectedSavedPasswordsIndexRouteImport.update({
    id: '/saved-passwords/',
    path: '/saved-passwords/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const AuthonlyNoAuthRegisterRoute = AuthonlyNoAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthonlyNoAuthRouteRoute,
} as any)
const AuthonlyNoAuthLoginRoute = AuthonlyNoAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthonlyNoAuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthonlyNoAuthRouteRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/login': typeof AuthonlyNoAuthLoginRoute
  '/auth/register': typeof AuthonlyNoAuthRegisterRoute
  '/saved-passwords/': typeof protectedSavedPasswordsIndexRoute
  '/settings/': typeof protectedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthonlyNoAuthRouteRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/login': typeof AuthonlyNoAuthLoginRoute
  '/auth/register': typeof AuthonlyNoAuthRegisterRoute
  '/saved-passwords': typeof protectedSavedPasswordsIndexRoute
  '/settings': typeof protectedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/auth/(only-no-auth)': typeof AuthonlyNoAuthRouteRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/(only-no-auth)/login': typeof AuthonlyNoAuthLoginRoute
  '/auth/(only-no-auth)/register': typeof AuthonlyNoAuthRegisterRoute
  '/(protected)/saved-passwords/': typeof protectedSavedPasswordsIndexRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/reset-password'
    | '/auth/reset-password-request'
    | '/api/auth/$'
    | '/auth/login'
    | '/auth/register'
    | '/saved-passwords/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/reset-password'
    | '/auth/reset-password-request'
    | '/api/auth/$'
    | '/auth/login'
    | '/auth/register'
    | '/saved-passwords'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/auth/(only-no-auth)'
    | '/auth/reset-password'
    | '/auth/reset-password-request'
    | '/api/auth/$'
    | '/auth/(only-no-auth)/login'
    | '/auth/(only-no-auth)/register'
    | '/(protected)/saved-passwords/'
    | '/(protected)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  AuthonlyNoAuthRouteRoute: typeof AuthonlyNoAuthRouteRouteWithChildren
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthResetPasswordRequestRoute: typeof AuthResetPasswordRequestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password-request': {
      id: '/auth/reset-password-request'
      path: '/auth/reset-password-request'
      fullPath: '/auth/reset-password-request'
      preLoaderRoute: typeof AuthResetPasswordRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/(only-no-auth)': {
      id: '/auth/(only-no-auth)'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthonlyNoAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/saved-passwords/': {
      id: '/(protected)/saved-passwords/'
      path: '/saved-passwords'
      fullPath: '/saved-passwords/'
      preLoaderRoute: typeof protectedSavedPasswordsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/auth/(only-no-auth)/register': {
      id: '/auth/(only-no-auth)/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthonlyNoAuthRegisterRouteImport
      parentRoute: typeof AuthonlyNoAuthRouteRoute
    }
    '/auth/(only-no-auth)/login': {
      id: '/auth/(only-no-auth)/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthonlyNoAuthLoginRouteImport
      parentRoute: typeof AuthonlyNoAuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface protectedRouteRouteChildren {
  protectedSavedPasswordsIndexRoute: typeof protectedSavedPasswordsIndexRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedSavedPasswordsIndexRoute: protectedSavedPasswordsIndexRoute,
  protectedSettingsIndexRoute: protectedSettingsIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface AuthonlyNoAuthRouteRouteChildren {
  AuthonlyNoAuthLoginRoute: typeof AuthonlyNoAuthLoginRoute
  AuthonlyNoAuthRegisterRoute: typeof AuthonlyNoAuthRegisterRoute
}

const AuthonlyNoAuthRouteRouteChildren: AuthonlyNoAuthRouteRouteChildren = {
  AuthonlyNoAuthLoginRoute: AuthonlyNoAuthLoginRoute,
  AuthonlyNoAuthRegisterRoute: AuthonlyNoAuthRegisterRoute,
}

const AuthonlyNoAuthRouteRouteWithChildren =
  AuthonlyNoAuthRouteRoute._addFileChildren(AuthonlyNoAuthRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  AuthonlyNoAuthRouteRoute: AuthonlyNoAuthRouteRouteWithChildren,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResetPasswordRequestRoute: AuthResetPasswordRequestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
