/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRequestRouteImport } from './routes/auth/reset-password-request'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthonlyNoAuthRouteRouteImport } from './routes/auth/(only-no-auth)/route'
import { Route as ApiPasswordsIndexRouteImport } from './routes/api/passwords/index'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as protectedSavedPasswordsIndexRouteImport } from './routes/(protected)/saved-passwords/index'
import { Route as AuthonlyNoAuthRegisterRouteImport } from './routes/auth/(only-no-auth)/register'
import { Route as AuthonlyNoAuthLoginRouteImport } from './routes/auth/(only-no-auth)/login'
import { Route as ApiPasswordsImportRouteImport } from './routes/api/passwords/import'
import { Route as ApiPasswordsExportRouteImport } from './routes/api/passwords/export'
import { Route as ApiPasswordsEditRouteImport } from './routes/api/passwords/edit'
import { Route as ApiPasswordsCreateRouteImport } from './routes/api/passwords/create'
import { Route as ApiPasswordsIdRouteImport } from './routes/api/passwords/$id'
import { Route as ApiAuthResetPasswordRequestRouteImport } from './routes/api/auth/reset-password-request'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthRefreshTokenRouteImport } from './routes/api/auth/refresh-token'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiPasswordsIdToggleFavouriteRouteImport } from './routes/api/passwords/$id.toggle-favourite'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRequestRoute =
  AuthResetPasswordRequestRouteImport.update({
    id: '/auth/reset-password-request',
    path: '/auth/reset-password-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthonlyNoAuthRouteRoute = AuthonlyNoAuthRouteRouteImport.update({
  id: '/auth/(only-no-auth)',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordsIndexRoute = ApiPasswordsIndexRouteImport.update({
  id: '/api/passwords/',
  path: '/api/passwords/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSavedPasswordsIndexRoute =
  protectedSavedPasswordsIndexRouteImport.update({
    id: '/saved-passwords/',
    path: '/saved-passwords/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const AuthonlyNoAuthRegisterRoute = AuthonlyNoAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthonlyNoAuthRouteRoute,
} as any)
const AuthonlyNoAuthLoginRoute = AuthonlyNoAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthonlyNoAuthRouteRoute,
} as any)
const ApiPasswordsImportRoute = ApiPasswordsImportRouteImport.update({
  id: '/api/passwords/import',
  path: '/api/passwords/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordsExportRoute = ApiPasswordsExportRouteImport.update({
  id: '/api/passwords/export',
  path: '/api/passwords/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordsEditRoute = ApiPasswordsEditRouteImport.update({
  id: '/api/passwords/edit',
  path: '/api/passwords/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordsCreateRoute = ApiPasswordsCreateRouteImport.update({
  id: '/api/passwords/create',
  path: '/api/passwords/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordsIdRoute = ApiPasswordsIdRouteImport.update({
  id: '/api/passwords/$id',
  path: '/api/passwords/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRequestRoute =
  ApiAuthResetPasswordRequestRouteImport.update({
    id: '/api/auth/reset-password-request',
    path: '/api/auth/reset-password-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshTokenRoute = ApiAuthRefreshTokenRouteImport.update({
  id: '/api/auth/refresh-token',
  path: '/api/auth/refresh-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordsIdToggleFavouriteRoute =
  ApiPasswordsIdToggleFavouriteRouteImport.update({
    id: '/toggle-favourite',
    path: '/toggle-favourite',
    getParentRoute: () => ApiPasswordsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthonlyNoAuthRouteRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh-token': typeof ApiAuthRefreshTokenRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/reset-password-request': typeof ApiAuthResetPasswordRequestRoute
  '/api/passwords/$id': typeof ApiPasswordsIdRouteWithChildren
  '/api/passwords/create': typeof ApiPasswordsCreateRoute
  '/api/passwords/edit': typeof ApiPasswordsEditRoute
  '/api/passwords/export': typeof ApiPasswordsExportRoute
  '/api/passwords/import': typeof ApiPasswordsImportRoute
  '/auth/login': typeof AuthonlyNoAuthLoginRoute
  '/auth/register': typeof AuthonlyNoAuthRegisterRoute
  '/saved-passwords/': typeof protectedSavedPasswordsIndexRoute
  '/settings/': typeof protectedSettingsIndexRoute
  '/api/passwords/': typeof ApiPasswordsIndexRoute
  '/api/passwords/$id/toggle-favourite': typeof ApiPasswordsIdToggleFavouriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthonlyNoAuthRouteRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh-token': typeof ApiAuthRefreshTokenRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/reset-password-request': typeof ApiAuthResetPasswordRequestRoute
  '/api/passwords/$id': typeof ApiPasswordsIdRouteWithChildren
  '/api/passwords/create': typeof ApiPasswordsCreateRoute
  '/api/passwords/edit': typeof ApiPasswordsEditRoute
  '/api/passwords/export': typeof ApiPasswordsExportRoute
  '/api/passwords/import': typeof ApiPasswordsImportRoute
  '/auth/login': typeof AuthonlyNoAuthLoginRoute
  '/auth/register': typeof AuthonlyNoAuthRegisterRoute
  '/saved-passwords': typeof protectedSavedPasswordsIndexRoute
  '/settings': typeof protectedSettingsIndexRoute
  '/api/passwords': typeof ApiPasswordsIndexRoute
  '/api/passwords/$id/toggle-favourite': typeof ApiPasswordsIdToggleFavouriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/auth/(only-no-auth)': typeof AuthonlyNoAuthRouteRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/reset-password-request': typeof AuthResetPasswordRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/refresh-token': typeof ApiAuthRefreshTokenRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/reset-password-request': typeof ApiAuthResetPasswordRequestRoute
  '/api/passwords/$id': typeof ApiPasswordsIdRouteWithChildren
  '/api/passwords/create': typeof ApiPasswordsCreateRoute
  '/api/passwords/edit': typeof ApiPasswordsEditRoute
  '/api/passwords/export': typeof ApiPasswordsExportRoute
  '/api/passwords/import': typeof ApiPasswordsImportRoute
  '/auth/(only-no-auth)/login': typeof AuthonlyNoAuthLoginRoute
  '/auth/(only-no-auth)/register': typeof AuthonlyNoAuthRegisterRoute
  '/(protected)/saved-passwords/': typeof protectedSavedPasswordsIndexRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
  '/api/passwords/': typeof ApiPasswordsIndexRoute
  '/api/passwords/$id/toggle-favourite': typeof ApiPasswordsIdToggleFavouriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/reset-password'
    | '/auth/reset-password-request'
    | '/api/auth/login'
    | '/api/auth/refresh-token'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/auth/reset-password-request'
    | '/api/passwords/$id'
    | '/api/passwords/create'
    | '/api/passwords/edit'
    | '/api/passwords/export'
    | '/api/passwords/import'
    | '/auth/login'
    | '/auth/register'
    | '/saved-passwords/'
    | '/settings/'
    | '/api/passwords/'
    | '/api/passwords/$id/toggle-favourite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/reset-password'
    | '/auth/reset-password-request'
    | '/api/auth/login'
    | '/api/auth/refresh-token'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/auth/reset-password-request'
    | '/api/passwords/$id'
    | '/api/passwords/create'
    | '/api/passwords/edit'
    | '/api/passwords/export'
    | '/api/passwords/import'
    | '/auth/login'
    | '/auth/register'
    | '/saved-passwords'
    | '/settings'
    | '/api/passwords'
    | '/api/passwords/$id/toggle-favourite'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/auth/(only-no-auth)'
    | '/auth/reset-password'
    | '/auth/reset-password-request'
    | '/api/auth/login'
    | '/api/auth/refresh-token'
    | '/api/auth/register'
    | '/api/auth/reset-password'
    | '/api/auth/reset-password-request'
    | '/api/passwords/$id'
    | '/api/passwords/create'
    | '/api/passwords/edit'
    | '/api/passwords/export'
    | '/api/passwords/import'
    | '/auth/(only-no-auth)/login'
    | '/auth/(only-no-auth)/register'
    | '/(protected)/saved-passwords/'
    | '/(protected)/settings/'
    | '/api/passwords/'
    | '/api/passwords/$id/toggle-favourite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  AuthonlyNoAuthRouteRoute: typeof AuthonlyNoAuthRouteRouteWithChildren
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthResetPasswordRequestRoute: typeof AuthResetPasswordRequestRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthRefreshTokenRoute: typeof ApiAuthRefreshTokenRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthResetPasswordRequestRoute: typeof ApiAuthResetPasswordRequestRoute
  ApiPasswordsIdRoute: typeof ApiPasswordsIdRouteWithChildren
  ApiPasswordsCreateRoute: typeof ApiPasswordsCreateRoute
  ApiPasswordsEditRoute: typeof ApiPasswordsEditRoute
  ApiPasswordsExportRoute: typeof ApiPasswordsExportRoute
  ApiPasswordsImportRoute: typeof ApiPasswordsImportRoute
  ApiPasswordsIndexRoute: typeof ApiPasswordsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password-request': {
      id: '/auth/reset-password-request'
      path: '/auth/reset-password-request'
      fullPath: '/auth/reset-password-request'
      preLoaderRoute: typeof AuthResetPasswordRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/(only-no-auth)': {
      id: '/auth/(only-no-auth)'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthonlyNoAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passwords/': {
      id: '/api/passwords/'
      path: '/api/passwords'
      fullPath: '/api/passwords/'
      preLoaderRoute: typeof ApiPasswordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/saved-passwords/': {
      id: '/(protected)/saved-passwords/'
      path: '/saved-passwords'
      fullPath: '/saved-passwords/'
      preLoaderRoute: typeof protectedSavedPasswordsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/auth/(only-no-auth)/register': {
      id: '/auth/(only-no-auth)/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthonlyNoAuthRegisterRouteImport
      parentRoute: typeof AuthonlyNoAuthRouteRoute
    }
    '/auth/(only-no-auth)/login': {
      id: '/auth/(only-no-auth)/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthonlyNoAuthLoginRouteImport
      parentRoute: typeof AuthonlyNoAuthRouteRoute
    }
    '/api/passwords/import': {
      id: '/api/passwords/import'
      path: '/api/passwords/import'
      fullPath: '/api/passwords/import'
      preLoaderRoute: typeof ApiPasswordsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passwords/export': {
      id: '/api/passwords/export'
      path: '/api/passwords/export'
      fullPath: '/api/passwords/export'
      preLoaderRoute: typeof ApiPasswordsExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passwords/edit': {
      id: '/api/passwords/edit'
      path: '/api/passwords/edit'
      fullPath: '/api/passwords/edit'
      preLoaderRoute: typeof ApiPasswordsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passwords/create': {
      id: '/api/passwords/create'
      path: '/api/passwords/create'
      fullPath: '/api/passwords/create'
      preLoaderRoute: typeof ApiPasswordsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passwords/$id': {
      id: '/api/passwords/$id'
      path: '/api/passwords/$id'
      fullPath: '/api/passwords/$id'
      preLoaderRoute: typeof ApiPasswordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password-request': {
      id: '/api/auth/reset-password-request'
      path: '/api/auth/reset-password-request'
      fullPath: '/api/auth/reset-password-request'
      preLoaderRoute: typeof ApiAuthResetPasswordRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh-token': {
      id: '/api/auth/refresh-token'
      path: '/api/auth/refresh-token'
      fullPath: '/api/auth/refresh-token'
      preLoaderRoute: typeof ApiAuthRefreshTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/passwords/$id/toggle-favourite': {
      id: '/api/passwords/$id/toggle-favourite'
      path: '/toggle-favourite'
      fullPath: '/api/passwords/$id/toggle-favourite'
      preLoaderRoute: typeof ApiPasswordsIdToggleFavouriteRouteImport
      parentRoute: typeof ApiPasswordsIdRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedSavedPasswordsIndexRoute: typeof protectedSavedPasswordsIndexRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedSavedPasswordsIndexRoute: protectedSavedPasswordsIndexRoute,
  protectedSettingsIndexRoute: protectedSettingsIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface AuthonlyNoAuthRouteRouteChildren {
  AuthonlyNoAuthLoginRoute: typeof AuthonlyNoAuthLoginRoute
  AuthonlyNoAuthRegisterRoute: typeof AuthonlyNoAuthRegisterRoute
}

const AuthonlyNoAuthRouteRouteChildren: AuthonlyNoAuthRouteRouteChildren = {
  AuthonlyNoAuthLoginRoute: AuthonlyNoAuthLoginRoute,
  AuthonlyNoAuthRegisterRoute: AuthonlyNoAuthRegisterRoute,
}

const AuthonlyNoAuthRouteRouteWithChildren =
  AuthonlyNoAuthRouteRoute._addFileChildren(AuthonlyNoAuthRouteRouteChildren)

interface ApiPasswordsIdRouteChildren {
  ApiPasswordsIdToggleFavouriteRoute: typeof ApiPasswordsIdToggleFavouriteRoute
}

const ApiPasswordsIdRouteChildren: ApiPasswordsIdRouteChildren = {
  ApiPasswordsIdToggleFavouriteRoute: ApiPasswordsIdToggleFavouriteRoute,
}

const ApiPasswordsIdRouteWithChildren = ApiPasswordsIdRoute._addFileChildren(
  ApiPasswordsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  AuthonlyNoAuthRouteRoute: AuthonlyNoAuthRouteRouteWithChildren,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthResetPasswordRequestRoute: AuthResetPasswordRequestRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthRefreshTokenRoute: ApiAuthRefreshTokenRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthResetPasswordRequestRoute: ApiAuthResetPasswordRequestRoute,
  ApiPasswordsIdRoute: ApiPasswordsIdRouteWithChildren,
  ApiPasswordsCreateRoute: ApiPasswordsCreateRoute,
  ApiPasswordsEditRoute: ApiPasswordsEditRoute,
  ApiPasswordsExportRoute: ApiPasswordsExportRoute,
  ApiPasswordsImportRoute: ApiPasswordsImportRoute,
  ApiPasswordsIndexRoute: ApiPasswordsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
