/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FastEndpointsErrorResponse {
  Errors?: {
    [key: string]: Array<string>;
  };
  Message?: string;
  StatusCode?: number;
}
