/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSavedPasswordUpdatePasswordResponse {
  CreatedAt?: string;
  Id?: string;
  Login?: string;
  Name?: string;
  Notes?: string;
  Password?: string;
  SecondLogin?: string | null;
  Tags?: Array<string>;
  UpdatedAt?: string;
  Url?: string;
}
