/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSavedPasswordDtOsImportExportPasswordDto } from '../models/user-saved-password-dt-os-import-export-password-dto';
export interface UserSavedPasswordDtOsImportExportDto {
  AUTHENTIFIANT: Array<UserSavedPasswordDtOsImportExportPasswordDto>;
}
