/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSavedPasswordCreatePasswordRequest {
  Login: string;
  Name: string;
  Notes?: string;
  Password: string;
  SecondLogin?: string;
  Tags?: Array<string>;
  Url?: string;
}
