/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSavedPasswordDtOsImportExportPasswordDto {
  domain?: string;
  login?: string;
  note?: string;
  password?: string;
  secondLogin?: string | null;
  tags?: Array<string> | null;
  title?: string;
}
