/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSavedPasswordGetPasswordsResponsePassword {
  CreatedAt?: string;
  Id?: string;
  Login?: string;
  Notes?: string;
  PasswordHash?: string;
  Tags?: Array<string>;
  UpdatedAt?: string;
  Url?: string;
}
