/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSavedPasswordGetPasswordsResponsePassword } from '../models/user-saved-password-get-passwords-response-password';
export interface UserSavedPasswordGetPasswordsResponse {
  passwords?: Array<UserSavedPasswordGetPasswordsResponsePassword>;
}
